general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ21N22"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  mtaBuild:
    source: cf
